default_language_version:
  python: python3
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [
            "-c"
        ]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
  - repo: local
    hooks:
    - id: poetry
      name: poetry check
      entry: poetry check
      pass_filenames: false
      language: system
      files: ^pyproject\.toml$
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.950
    hooks:
      - id: mypy
        args: [
            "--sqlite-cache"
        ]
        additional_dependencies: [pydantic>=1.9.0]
