"""init

Revision ID: f3719c0279ef
Revises:
Create Date: 2022-05-08 10:06:03.441556

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f3719c0279ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('username', sa.Text(), nullable=True),
        sa.Column('first_name', sa.Text(), nullable=True),
        sa.Column('last_name', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk__users')),
    )
    op.create_table(
        'accounts',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('owner_id', sa.BigInteger(), nullable=False),
        sa.Column('name', sa.Text(), nullable=False),
        sa.Column('balance', sa.Numeric(), nullable=False),
        sa.Column('currency', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(
            ['owner_id'], ['users.id'], name=op.f('fk__accounts__owner_id__users')
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk__accounts')),
    )
    op.create_table(
        'categories',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('name', sa.Text(), nullable=False),
        sa.Column('is_income', sa.Boolean(), server_default=sa.text('true'), nullable=False),
        sa.Column('is_outcome', sa.Boolean(), server_default=sa.text('true'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'], ['users.id'], name=op.f('fk__categories__user_id__users')
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk__categories')),
    )
    op.create_table(
        'accounts_users',
        sa.Column('account_id', sa.BigInteger(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(
            ['account_id'], ['accounts.id'], name=op.f('fk__accounts_users__account_id__accounts')
        ),
        sa.ForeignKeyConstraint(
            ['user_id'], ['users.id'], name=op.f('fk__accounts_users__user_id__users')
        ),
    )
    op.create_table(
        'transactions',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('at_date', sa.Date(), nullable=False),
        sa.Column('category_id', sa.BigInteger(), nullable=False),
        sa.Column('comment', sa.Text(), nullable=True),
        sa.Column('income_account_id', sa.BigInteger(), nullable=True),
        sa.Column('income_currency', sa.Text(), nullable=True),
        sa.Column('income', sa.Numeric(scale=2), nullable=True),
        sa.Column('outcome_account_id', sa.BigInteger(), nullable=True),
        sa.Column('outcome_currency', sa.Text(), nullable=True),
        sa.Column('outcome', sa.Numeric(scale=2), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(
            ['category_id'],
            ['categories.id'],
            name=op.f('fk__transactions__category_id__categories'),
        ),
        sa.ForeignKeyConstraint(
            ['income_account_id'],
            ['accounts.id'],
            name=op.f('fk__transactions__income_account_id__accounts'),
        ),
        sa.ForeignKeyConstraint(
            ['outcome_account_id'],
            ['accounts.id'],
            name=op.f('fk__transactions__outcome_account_id__accounts'),
        ),
        sa.ForeignKeyConstraint(
            ['user_id'], ['users.id'], name=op.f('fk__transactions__user_id__users')
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk__transactions')),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('accounts_users')
    op.drop_table('categories')
    op.drop_table('accounts')
    op.drop_table('users')
    # ### end Alembic commands ###
